use tienda;
SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
select nombre, precio, precio*1.07  from producto;
select nombre as "nom producte", precio as euros, precio*1.07 as dolars from producto;
select upper(nombre), precio from producto;
select lower(nombre), precio from producto;
select nombre, upper(substring(nombre,1,2)) as "primeres lletres" from producto;
select nombre, round(precio,0) as "preu arrodonit" from producto; 
select nombre, truncate(precio,0) as "preu truncate" from producto;
select  f.codigo from fabricante f right join producto p on f.codigo = p.codigo_fabricante; 
select distinct f.codigo from fabricante f right join producto p on f.codigo = p.codigo_fabricante; 
select nombre from fabricante order by nombre asc;
select nombre from fabricante order by nombre desc;
select nombre, precio from producto order by nombre asc, precio desc;
select * from fabricante limit 5;
select * from fabricante limit 2 offset 3;
select nombre, precio from producto order by precio asc limit 1;
select nombre, precio from producto order by precio desc limit 1;
select nombre from producto where codigo_fabricante=2;
select p.nombre, p.precio, f.nombre from producto p  join fabricante f on p.codigo_fabricante = f.codigo; 
select p.nombre, p.precio, f.nombre from producto p  join fabricante f on p.codigo_fabricante = f.codigo order by f.nombre; 
select p.codigo as codigo_fabricante, p.nombre as producto, f.codigo as codigo_fabricante, f.nombre as fabricante from producto p  join fabricante f on p.codigo_fabricante = f.codigo; 
select p.nombre, p.precio, f.nombre from producto p inner join fabricante f on p.codigo_fabricante = f.codigo  where p.precio = (select  min(precio) from producto); 
select p.nombre, p.precio,f.nombre from producto p inner join fabricante f on p.codigo_fabricante = f.codigo order by p.precio desc limit 1;
select p.*, f.nombre from producto p inner join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = "Lenovo";
select p.*,f.nombre from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = "Crucial " and p.precio > 200;
select p.*, f.nombre from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = "Asus" or f.nombre = "Hewlett-Packard" or f.nombre = "Seagate";
select p.*, f.nombre from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre in ("Asus", "Hewlett-Packard","Seagate");
select p.nombre as producte , p.precio, f.nombre as fabricante from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre like "%e";
select p.nombre as producte , p.precio, f.nombre as fabricante from producto p right join fabricante f on p.codigo_fabricante = f.codigo where f.nombre like "%w%";
select p.nombre as producte, p.precio, f.nombre as fabricante from producto p join fabricante f on p.codigo_fabricante = f.codigo where p.precio >=180 order by p.precio desc, p.nombre asc;
select distinct f.codigo, f.nombre from fabricante f right join producto p on f.codigo = p.codigo_fabricante;
select  f.codigo, f.nombre, p.* from fabricante f  left join  producto p on f.codigo = p.codigo_fabricante order by f.codigo;
select f.codigo, f.nombre from fabricante f left join producto p on f.codigo = p.codigo_fabricante where p.codigo_fabricante is null;
select p.*, f.nombre from fabricante f join producto p on f.codigo = p.codigo_fabricante where f.nombre = "Lenovo";
select * from producto where precio = (select p.precio from producto p join fabricante f on f.codigo = p.codigo_fabricante where f.nombre = "Lenovo" order by p.precio desc limit 1);
select p.nombre from producto p join fabricante f on f.codigo = p.codigo_fabricante where f.nombre = "Lenovo" order by p.precio desc limit 1;
select p.nombre from producto p join fabricante f on f.codigo = p.codigo_fabricante where f.nombre = "Hewlett-Packard" order by p.precio asc limit 1;
select * from producto where precio >= (select p.precio from producto p join fabricante f on f.codigo = p.codigo_fabricante where f.nombre = "Lenovo" order by p.precio desc limit 1);
select * from producto where precio >= (select avg(precio) from producto) and nombre = "Asus"; -- tots son menors, no hi ha asus de valor superior a 271.72 

use universidad;
select apellido1, apellido2, nombre from persona where tipo = "alumno" order by apellido1, apellido2, nombre;
select nombre, apellido1, apellido2 from persona where telefono is null and tipo = "alumno";
select * from persona where year(fecha_nacimiento) = "1999" and tipo = "alumno";
select * from persona where tipo = "profesor" and telefono is null and nif like "%K"; 
select * from asignatura where cuatrimestre = 1 and curso = 3 and id_grado = 7;
select p.apellido1, p.apellido2, p.nombre, d.nombre as "departamento" from persona p right join profesor pr on p.id = pr.id_profesor join departamento d on d.id = pr.id_departamento order by p.apellido1 asc , p.apellido2 asc, p.nombre asc;
select a.nombre, c.anyo_inicio, c.anyo_fin from  alumno_se_matricula_asignatura am join persona p on p.id= am.id_alumno join curso_escolar c on am.id_curso_escolar = c.id join asignatura a on am.id_asignatura = a.id where p.nif="26902806M";
select distinct d.nombre from departamento d  join profesor p on p.id_departamento=d.id  join asignatura a on a.id_profesor=p.id_profesor  join grado g on a.id_grado=g.id where g.nombre="Grado en Ingeniería Informática (Plan 2015)";
select distinct p.* from persona p right join alumno_se_matricula_asignatura a on a.id_alumno=p.id right join curso_escolar c on a.id_curso_escolar=c.id where c.anyo_inicio="2018";
-- Resol utilitzant left i right join
select d.nombre, p.apellido1, p.apellido2, p.nombre from persona p left join profesor pr on pr.id_profesor=p.id left join departamento d on d.id=pr.id_departamento; 
select pr.id_departamento, p.apellido1, p.apellido2, p.nombre from persona p left join profesor pr on pr.id_profesor=p.id where pr.id_departamento is null;
select d.nombre from departamento d left join profesor pr on d.id=pr.id_departamento where pr.id_departamento is null;
select p.apellido1, p.apellido2, p.nombre from persona p left join asignatura a on a.id_profesor=p.id where a.id is null;
select a.nombre, p.id from asignatura a left join persona p on a.id_profesor=p.id where id_profesor is null;
select * from departamento where id!=(select distinct d.id from departamento d right join profesor pr on d.id=pr.id_departamento right join asignatura a on a.id_profesor=pr.id_profesor right join alumno_se_matricula_asignatura al on al.id_asignatura=a.id where al.id_curso_escolar is not null);
-- consultes resum
select count(id) as "número d'alumnes" from persona where tipo="alumno";
select count(id) as "alumnos del 1999" from persona where year(fecha_nacimiento)="1999";
select count(pr.id_profesor) as "número de profesores", d.nombre from departamento d right join profesor pr on pr.id_departamento=d.id group by d.nombre order by count(pr.id_profesor) desc;
select g.nombre, count(a.id) as "número asignaturas" from grado g left join asignatura a on a.id_grado=g.id group by g.nombre having count(a.id)>40;
select g.nombre,a.tipo, sum(a.creditos) as "número de creditos" from grado g left join asignatura a on a.id_grado=g.id group by a.tipo, g.nombre having a.tipo is not null order by g.nombre;
select c.anyo_inicio as curso, count(distinct al.id_alumno) as "número de alumno inscritos" from alumno_se_matricula_asignatura al join curso_escolar c on c.id=al.id_curso_escolar group by al.id_curso_escolar;
select count(a.id) as "número de asignaturas" from asignatura a